steps:
  - id: "Rodando docker-compose"
    name: 'docker/compose'
    args: ['-f', 'docker-compose.yml', 'up', '-d']

  - id: "Rodando docker ps"
    name: 'docker'
    args: ['ps']

         
  - id: "Rodando testes"
    name: 'gcr.io/cloud-builders/go'
    args: ['test']
    env: ['GOPATH=/src']

  - id: "Build imagem Dockerfile"
    name: 'gcr.io/cloud-builders/docker' 
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/app-go:$SHORT_SHA', '-f', 'Dockerfile', '.']


  - id: "Push imagem Docker"
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/app-go:$SHORT_SHA']